### ISSUE TITLE
Don't halt the boot when AWS is not configured

### ISSUE THREAD

**Issue by james-hu** [coveo/spring-boot-parameter-store-integration#6]
Is it possible to catch the exception when AWS is not configured? Since by default a missing parameter won't stop the application from starting up, I suppose AWS connectivity and configuration issue shouldn't as well.

Current behaviour is the boot would be halt and this is the message:

com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:386)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:352)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClientBuilder.defaultClient(AWSSimpleSystemsManagementClientBuilder.java:44)
	at com.coveo.configuration.parameterstore.ParameterStorePropertySourceEnvironmentPostProcessor.buildAWSSimpleSystemsManagementClient(ParameterStorePropertySourceEnvironmentPostProcessor.java:60)
	at com.coveo.configuration.parameterstore.ParameterStorePropertySourceEnvironmentPostProcessor.postProcessEnvironment(ParameterStorePropertySourceEnvironmentPostProcessor.java:33)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:177)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)

**Comment by james-hu** [comment]
The exception itself I believe is a AWS SDK issue. I do have region in my ~/.aws/credentials file. And I worked around the issue by setting awsParameterStorePropertySource.enabled when not in prod. However, still think it would be good if the exception can be caught rather than thrown.

**Comment by fredboutin** [comment]
To prevent throwing and to have the default spring boot behaviour you can always set `awsParameterStorePropertySource.haltBoot: false`
Does this cover your usecase?

**Comment by fredboutin** [comment]
Oh I think I understand what you mean, haltBoot to false does not cover it. I think the proper way to do it is to disable the source like you did. Catching it would feel wrong since you specifically enabled it, so you would expect it to work and if it not to throw something.

**Comment by james-hu** [comment]
No problem. Thanks Fred.
